### PR TITLE
Add figure dependencies of the final report to Makefile.

### PR DESCRIPTION
**Pull request by stevenleung2018**
I have found an issue with the Makefile when I did some testing.

I tried to randomly delete some files and see if Makefile would behave correctly.  I notice that the Makefile, without the figure and some other files added to the final report, the Makefile would not try to rebuild the figures, etc., and the report generation would fail.

So I have changed the Makefile and tested that already.  Please try it on your computers.  Try to randomly delete some of the generated files and see whether this new Makefile works correctly for you.

### CODE REVIEW

**Comment by ming0701** [comment]
I am open to that and ok with either versions, but seems like adding those dependencies somehow duplicates the earlier parts of the makefile. I understand this change will make sure the makefile to run correctly when someone is randomly deleting the files, but I think we should assume the makefile is always run with the same files and file structure as our repo, or we have to cater many different scenarios.

**Comment by stevenleung2018** [comment]
@ming0701 Thanks for your comment.  I *let you guys decide* because the current version of the Makefile *still works* if:
1. The user doesn't delete any file generated by our scripts; and
2. The user doesn't play around with our code, e.g. change the age from 25 to 24.

(I just cannot "unsee" an issue I have seen during testing.  :-) )

Elaboration on the issue:
If the user does anything above, the current version of the Makefile will not work.  But there is a workaround - the user can `make clean` and then `make all` again.  So instead of accepting this pull request, we can just make a note under "Usage" saying that if something happens to `make all`, just do `make clean` and do `make all` again.

Regarding "cater many different scenarios", adding all dependencies of `doc/05_final_report.html` will do that once and for all, i.e. it covers ALL possible scenarios that will affect the dependencies, and `make all` will take care of generating the missing/changed dependencies again and the final report can always be generated.  In other words, the Makefile will be more robust.

**Comment by ming0701** [comment]
The user can always play around with our code and this is also one of the reasons why we put everything on git, or else we can just simply put final_report.pdf on git. What I think is, our make file should guarantee that the users can reproduce the outputs given everything is in the initial cloned state.  

The usage should be clear enough? There are 2 steps before you run the make file and the repository can be reset to the initial cloned state by make clean. If users would like to add one more step (e.g. randomly delete files) before "make all", this is out of our control. Even if we add another note, they can simply ignore it.

Screenshot 2021-12-04 at 10 33 34 AM

Using your logic of deleting files randomly, not likely this change will cover all possible scenarios. What if the user is moving the files to other folders randomly? What if the user deletes everything and leaving just the make file? If we want to cater all these scenarios, we may need to add cloning the repo as the very first part of the makefile.

I understand what you mentioned is likely to happen in the real situation, but I think this is outside the scope of this project. We better keep things simple here?

**Comment by stevenleung2018** [comment]
I'm closing this pull request due to Brandon's comments and the lack of consensus to change.  Have a nice weekend.

**Pull request closed without merging**
