### PR TITLE
Created 3 files and data download script

### PR DESCRIPTION
**Pull request by ming0701**
3 files:
i. Code of Conduct file
ii. Contributing file
iii. License file

### CODE REVIEW

**Review by stevenleung2018 — COMMENTED** [review]
Should we replace "Python community" with "project team" in the "Code of Conduct"?

**Comment by ming0701** [comment]
Yes, Steven, I will amend it in one go after our meeting today

**Review by stevenleung2018 — COMMENTED** [review]
@ming0701 Please note that I can only find the URL for downloading the data as a zip file.
Here is the URL: https://www.kaggle.com/stefanoleone992/imdb-extensive-dataset/download

For your convenience, I have found the following Python code for unzipping:

https://stackoverflow.com/questions/6861323/download-and-unzip-file-with-python/30327074

I believe we need to have the right code for unzipping and saving the CSV files under data/raw.

**Comment by ming0701** [comment]
The other way to solve this is to upload the CSV files so that we can get the direct link. I'm also fine with your solution, but this may make things complicated. Let's discuss further in our meeting.

**Review by stevenleung2018 — CHANGES_REQUESTED** [review]
@ming0701 As mentioned, please add code to handle the downloading of zip file and extracting the CSV file from it.

**Comment by ming0701** [comment]
hi all, i understand why tiffany not suggesting us to use kaggle. I changed the script to download the zip files and upzip it.  It is not likely we can download it through the script as login is required for kaggle. Anyone has idea on this? Shall we keep the original script? I will share the updated script in slack for your reference.

**Pull request merged**
