### PR TITLE
Final report rendering

### PR DESCRIPTION
**Pull request by ruben1dlg**
Hi guys! In this pull request I include the final report, the bibliography, and some additional documents I created (derived from the EDA and Htest rmd files), that I used as childs for the final report. Let me know if everything looks good!

### CODE REVIEW

**Comment by ming0701** [comment]
Everything looks good!
For limitations and assumptions, we may need to add one more point that the same athlete may participate in more than one events and in different years, so there are multiple records for the same athlete, but we calculate the portion based on the records.

**Comment by ruben1dlg** [comment]
Thanks @ming0701 ! I've committed the change!

**Review by ming0701 — APPROVED** [review]

**Comment by stevenleung2018** [comment]
I am reviewing only from the output HTML file.  I believe it should be sufficient for our purposes since the HTML can be generated without errors.

I have spotted the following typos:

1. In the first line under "Summary", it should look like the following:

**Here we attempt to perform a hypothesis test on the question, "Is the proportion of athletes younger than 25 that win a medal greater than the proportion of athletes of age 25 or older that win a medal?"**

The quotation marks are missing from you text and there is an extra period after the question mark.

2. In the first line under "Introduction", "Olympic" should be capitalized like this.  

3. Last word of the 1st line under "Introduction", the last word should be spent as "strength".

Other issues:

1. The "Simulation-Based Null Distribution" figure, we should number it "Figure 5" instead of "Figure 1".  This is also true with the 2 tables under "Results & Discussion".  They should be numbers "Table 3" and "Table 4".

Other comment:

Limitations and assumptions (under Introduction) are really good!

Since the above issues are minor, I'm ok with merging the pull request.

**Review by stevenleung2018 — APPROVED** [review]
Please review the list of minor issues I wrote in the comment to the pull request.  Otherwise it is ready for merging.

**Comment by ming0701** [comment]
I have updated the 04_htest.Rmd file for the tables and figures number. The changes have been merged.
Ruben please generate the final report again. Thanks

**Comment by ruben1dlg** [comment]
I've committed the changes for the typos that @stevenleung2018 mentioned, and also generated the final report with the correct numbers for the tables and figures after @ming0701 changed it 👍🏻

**Review by ming0701 — APPROVED** [review]

**Pull request merged**
