### PR TITLE
Update README and create environment.yaml

### PR DESCRIPTION
**Pull request by squisty**

### CODE REVIEW

**Review by stevenleung2018 — CHANGES_REQUESTED** [review]
I have found a strange issue with the environment and R.

This is the command:

Rscript -e "rmarkdown::render('results/03_EDA.Rmd')"

If I am in my base environment, it can knit the HTML file just fine.

But after I have done `conda activate olympic_env`, I run into the following error:

$ Rscript -e "rmarkdown::render('results/03_EDA.Rmd')"
Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
Execution halted

I will try to find out on my end.  Please also check on your end as well.

**Comment by stevenleung2018** [comment]
@squisty I resolved the issue by running `brew install pandoc` from command line.  Here are the messages:

(You may ignore the messages related to updating my Homebrew.)

$ brew install pandoc
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/services).
==> New Formulae
actionlint                  goproxy                     pip-tools
all-repos                   gotests                     pkg-config-wrapper
apache-pulsar               gtop                        pkgconf
atmos                       iproute2                    postgresql@13
aws-sso-util                iputils                     python-tk@3.10
bat-extras                  jellyfish                   python@3.10
bottom                      jpdfbookmarks               qwt-qt5
ca-certificates             k2tf                        rbw
cassandra@3                 kube-score                  red-tldr
cgif                        kubeval                     regula
charmcraft                  lastz                       rizin
clang-format@11             ld-find-code-refs           rustfmt
clickhouse-cpp              libavif                     sextractor
clickhouse-odbc             libnghttp2                  sigrok-cli
cloudiscovery               librist                     smug
cmake-docs                  libsigrok                   spdx-sbom-generator
colima                      libsigrokdecode             swiftplantuml
copier                      libsoup@2                   symengine
corepack                    libxls                      tailscale
cpufetch                    lilypond                    terraform-rover
cri-tools                   liqoctl                     texlive
cyral-gimme-db-token        llvm@12                     tfk8s
datafusion                  luau                        tfmigrate
feroxbuster                 lunzip                      tfproviderlint
fheroes2                    ly                          tfupdate
fisher                      lziprecover                 tilt
fnlfmt                      mdzk                        toml11
g2o                         mmtabbarview                twty
git-cliff                   ncnn                        urlwatch
git-credential-libsecret    neovim-qt                   uuu
git-svn                     node@16                     viddy
gitlab-ci-local             nsh                         viu
go-critic                   openssl@3                   west
gomodifytags                pdf2djvu                    youtubeuploader
==> Updated Formulae
Updated 4880 formulae.
==> Renamed Formulae
rt-audio -> rtaudio
selenium-server-standalone -> selenium-server
==> Deleted Formulae
amap                        pandoc-citeproc             vavrdiasm
ocamlsdl                    soundpipe

==> Downloading https://ghcr.io/v2/homebrew/core/pandoc/manifests/2.16.2
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pandoc/blobs/sha256:65b87339c01f5
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha2
######################################################################## 100.0%
==> Pouring pandoc--2.16.2.arm64_monterey.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /opt/homebrew/etc/bash_completion.d
==> Summary
🍺  /opt/homebrew/Cellar/pandoc/2.16.2: 10 files, 235.2MB
==> `brew cleanup` has not been run in the last 30 days, running now...
Removing: /Users/stevenprivate/Library/Caches/Homebrew/bash--5.1.8... (3.0MB)
Removing: /Users/stevenprivate/Library/Caches/Homebrew/gdbm--1.20... (222.3KB)
Removing: /Users/stevenprivate/Library/Caches/Homebrew/git-gui--2.33.0... (479.8KB)
Removing: /Users/stevenprivate/Library/Caches/Homebrew/postgresql--13.4... (10.9MB)
Removing: /Users/stevenprivate/Library/Caches/Homebrew/python@3.9--3.9.7... (13.6MB)
Removing: /Users/stevenprivate/Library/Caches/Homebrew/readline--8.1... (559.2KB)
Removing: /Users/stevenprivate/Library/Caches/Homebrew/tcl-tk--8.6.11_1... (8.4MB)
Removing: /Users/stevenprivate/Library/Logs/Homebrew/postgresql... (1.3KB)
Removing: /Users/stevenprivate/Library/Logs/Homebrew/git-gui... (64B)
Removing: /Users/stevenprivate/Library/Logs/Homebrew/icu4c... (64B)
Removing: /Users/stevenprivate/Library/Logs/Homebrew/bash... (64B)
Removing: /Users/stevenprivate/Library/Logs/Homebrew/krb5... (64B)
Removing: /Users/stevenprivate/Library/Logs/Homebrew/tcl-tk... (64B)
Removing: /Users/stevenprivate/Library/Logs/Homebrew/python@3.9... (2 files, 2.5KB)

Since we know how to resolve this, I'm ok with the merge and perhaps we just need to add a note or something about the dependency with `pandoc` and how to install, etc.

**Comment by ming0701** [comment]
Thanks Sam, please find my comments below,
Readme:
- please add report section with link to the final report, you may refer to (https://github.com/ttimbers/breast_cancer_predictor/tree/v2.0)
- add references

test.md:
do we need this file? if not, please delete it.

**Review by stevenleung2018 — APPROVED** [review]
I'm approving this pull request.  I have tested with the commands in the README.md and I can run to the start to end AFTER installing `pandoc`.

**Pull request merged**
