### PR TITLE
Complete EDA for the dataset.

### PR DESCRIPTION
**Pull request by stevenleung2018**

### CODE REVIEW

**Comment by ming0701** [comment]
Thanks Steven, the EDA looks great. Below are a few minor comments for your consideration,
1. Budget is likely another important feature for predicting box office, but it is not included in the EDA. I noticed that there are many miss values for budget and the column will needed to be cleaned.
2. Higher metascore is more likely to have higher worldwide gross income? (your comment said they are not correlated)
3. Positive correlation of year and worldwide gross income because of inflation ($10 50 years ago worth more than $10 today), shall we add that to explain the trend? Good to see there are some exceptions (e.g Titanic in 1997)

**Comment by stevenleung2018** [comment]
Thanks for the comments.

1. I have made it a bit more explicit that 'budget' has a lot of missing values.  I do not want to do more EDA beyond just saying that as it will require a bit of effort trying to clean it.  Plus if there are too many missing values, it may not be very useful anyway.  (In real life, many companies don't disclose the budget of a movie.)  XD
2. Thanks for the input.  I will change it to correlated positively but not strong.
3. Adding the word inflation.  (I was thinking that it was too obvious.  But let's put it there.)

**Review by squisty — CHANGES_REQUESTED** [review]
create md or html file if possible

**Comment by stevenleung2018** [comment]
> create md or html file if possible

I have just exported the md and the associated png files for readability.

**Comment by stevenleung2018** [comment]
@squisty including now the md file and the associated png files for readability.

**Review by ruben1dlg — APPROVED** [review]

**Review by ming0701 — APPROVED** [review]

**Pull request merged**
